# Foundation CLI/TUI tools - sorted alphabetically
brew "atuin"
brew "bat"
brew "btop"
brew "carapace"
brew "clipboard"
brew "direnv"
brew "eza"
brew "ffmpeg"
brew "fzf"
brew "gdu"
brew "gh"
brew "git"
brew "git-lfs"
brew "jj"
brew "jq"
brew "lazydocker"
brew "lazygit"
brew "lazyjj"
brew "neovim"
brew "starship"
brew "stow"
brew "uv"
brew "yazi"
brew "yq"
brew "zoxide"

# Casks - sorted alphabetically
cask "espanso"
cask "ghostty"
cask "karabiner-elements"
